services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dimdimdb
      MYSQL_USER: dimdim
      MYSQL_PASSWORD: dimdimpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dimdim-net

  app:
    build: ./backend
    container_name: dimdim_app
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dimdimdb
      SPRING_DATASOURCE_USERNAME: dimdim
      SPRING_DATASOURCE_PASSWORD: dimdimpass
    ports:
      - "8080:8080"
    user: "1000:1000"   # usuário sem privilégios root
    networks:
      - dimdim-net

volumes:
  db_data:

networks:
  dimdim-net:
    driver: bridge
